site_name: MDS
site_description: "A Mortar design system implementation for Android."
site_author: Eggman87 Apps.
theme:
  name: mkdocs
  locale: en
  user_color_mode_toggle: true

nav:
  - 'Overview': index.md
  - 'Dev Guide': dev_guide.md
  - 'Testing': testing.md